name: cli_dart
description: Dart CLI for CL Client
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  crypto: ^3.0.7
  encrypt: ^5.0.3
  cl_server_dart_client:
    path: ../../sdks/dartsdk

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.3
  mocktail: ^1.0.1
  lints: ^3.0.0

executables:
  cli-dart: cli_dart
